import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'

const root = fileURLToPath(new URL('.', import.meta.url))
const viewBoxes: Record<string, string> = {}
const entries = readdirSync(join(root, 'svg')).filter((name) => name.endsWith('.svg')).sort().map((file) => {
  const source = readFileSync(join(root, 'svg', file), 'utf8').replace(/<!--[\s\S]*?-->/g, '').trim()
  const match = /^<svg\b([^>]*)>([\s\S]*)<\/svg>$/.exec(source)
  const viewBox = match && /viewBox=["']([^"']+)["']/.exec(match[1]!)?.[1]
  if (!match || !viewBox) throw new Error(`${file}: missing SVG viewBox`)
  viewBoxes[file.slice(0, -4)] = viewBox
  return `  ${JSON.stringify(file.slice(0, -4))}: ${JSON.stringify(match[2]!.trim())},`
})
writeFileSync(join(root, 'src/icons.ts'), [
  '// Generated by build-icons.ts from ../svg. Run bun run icons:build to regenerate.',
  "export const ICON_VIEWBOX = '0 0 24 24'", '',
  'export const icons = {', ...entries, '} as const', '',
  'export type IconName = keyof typeof icons', '',
  `export const iconViewBoxes: Record<IconName, string> = ${JSON.stringify(viewBoxes, null, 2)}`, '',
].join('\n'))
